package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseNewsUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsUsers extends BaseNewsUsers<NewsUsers> {
	public static final NewsUsers dao = new NewsUsers().dao();
}
