package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseStrategy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Strategy extends BaseStrategy<Strategy> {
	public static final Strategy dao = new Strategy().dao();
}
