package cn.jbolt.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;

import cn.jbolt.common.model.base.BaseTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Topic extends BaseTopic<Topic> {
	public static final Topic dao = new Topic().dao();
	
	public List<Topic>list(){
		List<Topic> result=Topic.dao.find("select * from topic");
		System.out.println("s");
		return result;
	}
	public long count(){
		long count=Db.queryLong("select count(*) from topic");
		return count;
	}
}
