package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public M setNid(java.lang.Integer nid) {
		set("nid", nid);
		return (M)this;
	}
	
	public java.lang.Integer getNid() {
		return getInt("nid");
	}

	public M setNtid(java.lang.Integer ntid) {
		set("ntid", ntid);
		return (M)this;
	}
	
	public java.lang.Integer getNtid() {
		return getInt("ntid");
	}

	public M setNtitle(java.lang.String ntitle) {
		set("ntitle", ntitle);
		return (M)this;
	}
	
	public java.lang.String getNtitle() {
		return getStr("ntitle");
	}

	public M setNauthor(java.lang.String nauthor) {
		set("nauthor", nauthor);
		return (M)this;
	}
	
	public java.lang.String getNauthor() {
		return getStr("nauthor");
	}

	public M setNcreateDate(java.util.Date ncreateDate) {
		set("ncreateDate", ncreateDate);
		return (M)this;
	}
	
	public java.util.Date getNcreateDate() {
		return get("ncreateDate");
	}

	public M setNpicPath(java.lang.String npicPath) {
		set("npicPath", npicPath);
		return (M)this;
	}
	
	public java.lang.String getNpicPath() {
		return getStr("npicPath");
	}

	public M setNcontent(java.lang.String ncontent) {
		set("ncontent", ncontent);
		return (M)this;
	}
	
	public java.lang.String getNcontent() {
		return getStr("ncontent");
	}

	public M setNmodifyDate(java.util.Date nmodifyDate) {
		set("nmodifyDate", nmodifyDate);
		return (M)this;
	}
	
	public java.util.Date getNmodifyDate() {
		return get("nmodifyDate");
	}

	public M setNsummary(java.lang.String nsummary) {
		set("nsummary", nsummary);
		return (M)this;
	}
	
	public java.lang.String getNsummary() {
		return getStr("nsummary");
	}

}
