package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStrategy<M extends BaseStrategy<M>> extends Model<M> implements IBean {

	public M setSid(java.lang.Integer sid) {
		set("sid", sid);
		return (M)this;
	}
	
	public java.lang.Integer getSid() {
		return getInt("sid");
	}

	public M setSname(java.lang.String sname) {
		set("sname", sname);
		return (M)this;
	}
	
	public java.lang.String getSname() {
		return getStr("sname");
	}

	public M setMyield(java.lang.String myield) {
		set("myield", myield);
		return (M)this;
	}
	
	public java.lang.String getMyield() {
		return getStr("myield");
	}

	public M setFyield(java.lang.String fyield) {
		set("fyield", fyield);
		return (M)this;
	}
	
	public java.lang.String getFyield() {
		return getStr("fyield");
	}

	public M setAyield(java.lang.String ayield) {
		set("ayield", ayield);
		return (M)this;
	}
	
	public java.lang.String getAyield() {
		return getStr("ayield");
	}

	public M setMdrawdown(java.lang.String mdrawdown) {
		set("mdrawdown", mdrawdown);
		return (M)this;
	}
	
	public java.lang.String getMdrawdown() {
		return getStr("mdrawdown");
	}

	public M setTfrequency(java.lang.String tfrequency) {
		set("tfrequency", tfrequency);
		return (M)this;
	}
	
	public java.lang.String getTfrequency() {
		return getStr("tfrequency");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setGearing(java.lang.String gearing) {
		set("gearing", gearing);
		return (M)this;
	}
	
	public java.lang.String getGearing() {
		return getStr("gearing");
	}

	public M setIncomerisk(java.lang.String incomerisk) {
		set("incomerisk", incomerisk);
		return (M)this;
	}
	
	public java.lang.String getIncomerisk() {
		return getStr("incomerisk");
	}

	public M setWinning(java.lang.String winning) {
		set("winning", winning);
		return (M)this;
	}
	
	public java.lang.String getWinning() {
		return getStr("winning");
	}

	public M setProfit(java.lang.String profit) {
		set("profit", profit);
		return (M)this;
	}
	
	public java.lang.String getProfit() {
		return getStr("profit");
	}

	public M setDaysoffirmoffer(java.lang.String daysoffirmoffer) {
		set("daysoffirmoffer", daysoffirmoffer);
		return (M)this;
	}
	
	public java.lang.String getDaysoffirmoffer() {
		return getStr("daysoffirmoffer");
	}

}
