package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComments<M extends BaseComments<M>> extends Model<M> implements IBean {

	public M setCid(java.lang.Integer cid) {
		set("cid", cid);
		return (M)this;
	}
	
	public java.lang.Integer getCid() {
		return getInt("cid");
	}

	public M setCnid(java.lang.Integer cnid) {
		set("cnid", cnid);
		return (M)this;
	}
	
	public java.lang.Integer getCnid() {
		return getInt("cnid");
	}

	public M setCcontent(java.lang.String ccontent) {
		set("ccontent", ccontent);
		return (M)this;
	}
	
	public java.lang.String getCcontent() {
		return getStr("ccontent");
	}

	public M setCdate(java.util.Date cdate) {
		set("cdate", cdate);
		return (M)this;
	}
	
	public java.util.Date getCdate() {
		return get("cdate");
	}

	public M setCip(java.lang.String cip) {
		set("cip", cip);
		return (M)this;
	}
	
	public java.lang.String getCip() {
		return getStr("cip");
	}

	public M setCauthor(java.lang.String cauthor) {
		set("cauthor", cauthor);
		return (M)this;
	}
	
	public java.lang.String getCauthor() {
		return getStr("cauthor");
	}

	public M setUid(java.lang.Integer uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public M setUuid(java.lang.Integer uuid) {
		set("uuid", uuid);
		return (M)this;
	}
	
	public java.lang.Integer getUuid() {
		return getInt("uuid");
	}

}
