package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public M setTid(java.lang.Integer tid) {
		set("tid", tid);
		return (M)this;
	}
	
	public java.lang.Integer getTid() {
		return getInt("tid");
	}

	public M setTname(java.lang.String tname) {
		set("tname", tname);
		return (M)this;
	}
	
	public java.lang.String getTname() {
		return getStr("tname");
	}

}
