package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNewsUsers<M extends BaseNewsUsers<M>> extends Model<M> implements IBean {

	public M setUid(java.lang.Integer uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public M setUname(java.lang.String uname) {
		set("uname", uname);
		return (M)this;
	}
	
	public java.lang.String getUname() {
		return getStr("uname");
	}

	public M setUpwd(java.lang.String upwd) {
		set("upwd", upwd);
		return (M)this;
	}
	
	public java.lang.String getUpwd() {
		return getStr("upwd");
	}

}
